# This file is a template, and might need editing before it works on your project.
image: registry.gitlab.com/tsocial/docker-images/golang-pipeline-runner:develop_4fd5c13f9af5f67cd7e72ffd186175604bf71b8e
services:
    - docker:dind
    
variables:
  # Please edit to your GitLab project
#   REPO_NAME: gitlab.com/tsocial/sre/tessellate

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
    # - apk add --update unzip
    # - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
    # - mkdir -p /opt/terraform && unzip terraform.zip -d /opt/terraform
    # - ln -s /opt/terraform/terraform /usr/bin/terraform
    # - rm -f terraform.zip
    - make protodep
    - export PROTO_VERSION=3.5.1
    - export PATH="/tmp/proto/${PROTO_VERSION}/bin/":$PATH
    - make build_deps
    - docker-compose -f docker-compose.yaml up -d consul

stages:
    - test
    - build

test::unit_test:
    stage: test
    script:
        - make test
    
build:
    stage: build
    script:
        - make worker_build
        - make http_build
        - make cli_build
        - make tessellate_build
        - make build_images
