# This file is a template, and might need editing before it works on your project.
image: registry.gitlab.com/tsocial/docker-images/golang-pipeline-runner:develop_109298fe900316ae48658a1cb16a242ac14fbf64

services:
    - docker:dind
    
variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/tsocial/sre/tessellate

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.

before_script:
    - make protodep
    - export PROTO_VERSION=3.5.1
    - export PATH="/tmp/proto/${PROTO_VERSION}/bin/":$PATH
    
    # Debug
    - pwd
    - echo $PATH
    - echo $GOPATH
    - ls /builds/tsocial/sre/tessellate

    - mkdir -p $GOPATH/src/gitlab.com/tsocial/sre
    - cp -R /builds/tsocial/sre/tessellate $GOPATH/src/gitlab.com/tsocial/sre
    - cd $GOPATH/src/gitlab.com/tsocial/sre/tessellate

    - make build_deps

    - docker-compose -f docker-compose.yaml up -d consul

stages:
    - test
    - build

test::unit_test:
    stage: test
    script:
        - cd $GOPATH/src/gitlab.com/tsocial/sre/tessellate
        - make test
    
build:
    stage: build
    script:
        - cd $GOPATH/src/gitlab.com/tsocial/sre/tesselate
        - make worker_build
        - make http_build
        - make cli_build
        - make tessellate_build
        - make build_images
        
