language: go

go:
  - "1.10"

services:
  - docker

script:
  - docker-compose -f docker-compose.yaml up -d consul
  - make test

deploy:
  - provider: script
    script: make upload_docker_images
    on:
      branch: master
