language: go

go:
  - "1.10"

services:
  - docker

script:
  - make build_deps
  - export PROTO_VERSION=3.5.1
  - export PATH="/tmp/proto/${PROTO_VERSION}/bin/":$PATH
  - docker-compose -f docker-compose.yaml up -d consul
  - make worker_build
  - make http_build
  - make cli_build
  - make tessellate_build
  - make test

deploy:
  - provider: script
    script: make upload_images
    on:
      branch: master
