version: '2.0'
services:
  consul:
    image: consul:1.2.0
    ports:
      - 8500:8500
      - 8600:8600
      - 8400:8400
  worker:
    build:
      context: .
      dockerfile: WorkerDockerfile
    image: tsl8/worker
    command: --job=123 --workspace=123 --consul-host=consul:8500
  grpc-server:
    build:
      context: .
      dockerfile: ServerDockerfile
    image: tsl8/grpc-server
#  http:
#    build:
#      context: .
#      dockerfile: HttpDockerfile
#    image: tsl8/api
